# Generated by Django 4.1.2 on 2022-10-24 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_news_article_alter_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLUB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellphone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('instagram', models.URLField()),
                ('description_1', models.CharField(max_length=800)),
                ('description_2', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='PLACE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='STUDENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rut', models.IntegerField()),
                ('date_birth', models.CharField(max_length=200)),
                ('e_number', models.CharField(max_length=200)),
                ('e_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EVENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('days', models.CharField(max_length=200)),
                ('hours', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=800)),
                ('img', models.ImageField(upload_to='')),
                ('id_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.place')),
            ],
        ),
        migrations.CreateModel(
            name='ENROLLMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.place')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='ATTENDANCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('id_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.place')),
            ],
        ),
    ]
