# Generated by Django 4.1.3 on 2022-11-24 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_event_type_division"),
    ]

    operations = [
        migrations.CreateModel(
            name="EMERGENCY_CONTACT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("rut", models.IntegerField()),
                ("phone", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(model_name="event", name="id_place",),
        migrations.RenameField(
            model_name="student", old_name="date_birth", new_name="birthday",
        ),
        migrations.RenameField(
            model_name="student", old_name="e_name", new_name="health",
        ),
        migrations.RemoveField(model_name="club", name="description_1",),
        migrations.RemoveField(model_name="club", name="description_2",),
        migrations.RemoveField(model_name="enrollment", name="id_place",),
        migrations.RemoveField(model_name="student", name="e_number",),
        migrations.AddField(
            model_name="club",
            name="articleA",
            field=models.CharField(default="VACIO", max_length=800),
        ),
        migrations.AddField(
            model_name="club",
            name="articleB",
            field=models.CharField(default="VACIO", max_length=800),
        ),
        migrations.AddField(
            model_name="club",
            name="articleC",
            field=models.CharField(default="VACIO", max_length=800),
        ),
        migrations.AddField(
            model_name="club",
            name="imgDown",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="club",
            name="imgEvents",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="club",
            name="imgSchedule",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="club",
            name="imgUp",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="club",
            name="titleA",
            field=models.CharField(default="VACIO", max_length=200),
        ),
        migrations.AddField(
            model_name="club",
            name="titleB",
            field=models.CharField(default="VACIO", max_length=200),
        ),
        migrations.AddField(
            model_name="club",
            name="titleC",
            field=models.CharField(default="VACIO", max_length=200),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="id_division",
            field=models.ForeignKey(
                default="VACIO",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.division",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="id_student",
            field=models.ForeignKey(
                default="VACIO",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.student",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="img",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(default="VACIO", max_length=200),
        ),
        migrations.DeleteModel(name="ATTENDANCE",),
        migrations.DeleteModel(name="EVENT",),
        migrations.AddField(
            model_name="student",
            name="id_emergency",
            field=models.ForeignKey(
                default="VACIO",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.emergency_contact",
            ),
        ),
    ]
