# Generated by Django 4.1.3 on 2022-12-02 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_enrollment_id_division_and_more"),
    ]

    operations = [
        migrations.RenameField(model_name="club", old_name="imgDown", new_name="imgA",),
        migrations.RenameField(model_name="club", old_name="imgUp", new_name="imgB",),
        migrations.RenameField(
            model_name="club", old_name="articleA", new_name="intro",
        ),
        migrations.RenameField(
            model_name="club", old_name="articleB", new_name="mision",
        ),
        migrations.RenameField(
            model_name="club", old_name="titleA", new_name="titleIntro",
        ),
        migrations.RenameField(
            model_name="club", old_name="titleB", new_name="titleMision",
        ),
        migrations.RenameField(
            model_name="club", old_name="titleC", new_name="titleVision",
        ),
        migrations.RenameField(
            model_name="club", old_name="articleC", new_name="vision",
        ),
    ]
