# Generated by Django 4.1.3 on 2022-12-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_rename_imgdown_club_imga_rename_imgup_club_imgb_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="club", name="imgB",),
        migrations.RemoveField(model_name="club", name="titleMision",),
        migrations.RemoveField(model_name="club", name="titleVision",),
        migrations.AddField(
            model_name="division", name="register", field=models.URLField(default=""),
        ),
    ]
