# Generated by Django 4.1.3 on 2022-12-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_remove_club_imgb_remove_club_titlemision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club", name="cellphone", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="imgA",
            field=models.ImageField(blank=True, default=None, upload_to=""),
        ),
        migrations.AlterField(
            model_name="club",
            name="imgEvents",
            field=models.ImageField(blank=True, default=None, upload_to=""),
        ),
        migrations.AlterField(
            model_name="club",
            name="imgSchedule",
            field=models.ImageField(blank=True, default=None, upload_to=""),
        ),
        migrations.AlterField(
            model_name="club", name="instagram", field=models.URLField(null=True),
        ),
    ]
